apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: web
type: Opaque
data:
  nvidiaAPIKey: {{ include "h2oai-floodprediction.nvidiaApiKey" . | b64enc | quote }}
  h2ogpteAPIKey: {{ include "h2oai-floodprediction.h2ogpteAPIKey" . | b64enc | quote }}
